version: "3"
services:
  api:
    image: matrixacr.azurecr.io/rythm-app:latest
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: matrixacr.azurecr.io/rythm-app:latest
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
